server:
  port: 8091

spring:
  application:
    name: peak-small
  rabbitmq:
    host: 118.25.123.16
    port: 5672
    username: root
    password: admin
    #publisher-confirms: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://118.25.123.16:3306/pkk-shiro?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: kunzai
    password: FFgL5O9HCe6PK!RE
    hikari:
      data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: 118.25.123.16
    password: RHK#c2GxARQqfho8
    port: 6379
    database: 0
  mvc:
      throw-exception-if-no-handler-found: true
  resources:
      add-mappings: false



mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.pkk.peaksmall.module

eureka:
  client:
     healthcheck:
          #开启健康检查（需要spring-boot-starter-actuator依赖）
          enabled: true
     service-url:
      defaultZone: http://118.25.123.16:8761/eureka
  instance:
      prefer-ip-address: true
      #租期更新时间间隔（默认30秒）
      lease-renewal-interval-in-seconds: 10
      #租期到期时间（默认90秒）
      lease-expiration-duration-in-seconds: 30

logging:
  com:
    pkk: debug