spring:
  rabbitmq:
    username: root
    password: admin
    port: 5672
    host: 118.25.123.16
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://118.25.123.16:3306/pkk-shiro?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: kunzai
    password: FFgL5O9HCe6PK!RE
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

