spring:
  freemarker:
    cache: false
  redis:
    database: 7
    host: 101.37.64.127
    port: 6379
    password: k7lla2rL7qdR9vP2
  rabbitmq:
    host: 117.143.217.94
    port: 5672
    username: rabbit
    password: rabbit@admin
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://118.25.123.16:3305/bynamic-ds?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      username: dev_user3306
      password: dev_user3306


eureka:
  client:
    service-url:
      defaultZone: http://118.25.123.16:8761/eureka
    registry-fetch-interval-seconds: 5

#rabbit:
#  listener:
#    prefetchCount: 100
#    concurrentConsumers: 500

#quartz:
#  threadCount: 100


#logging
logging:
  level.com.zhiyi: debug
  level.java.sql.Connection: debug
  level.java.sql.Statement: debug
  level.java.sql.PreparedStatement: debug
