spring:
  freemarker:
    cache: false
  redis:
    database: 7
    host: 101.37.64.127
    port: 6379
    password: k7lla2rL7qdR9vP2
  rabbitmq:
    host: 118.25.123.16
    port: 5672
    username: root
    password: admin
  datasource:
    hikari:
      #jdbc-url: jdbc:mysql://118.25.123.16:3306/dynamic_ds?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      jdbc-url: jdbc:mysql://localhost:3306/dynamic_ds?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      username: kunzai
      password: FFgL5O9HCe6PK!RE
      connection-timeout: 60000
      connection-test-query: select 1
      driver-class-name: com.mysql.cj.jdbc.Driver


penguin:
  dynamic:
    datasource:
      ssh:
        enable: true
        remoteSshUser: root
        remoteSshPwd: "@Wasd12345"
        remoteSshHost: 118.25.123.16


eureka:
  client:
    service-url:
      defaultZone: http://118.25.123.16:8761/eureka
    registry-fetch-interval-seconds: 5

#rabbit:
#  listener:
#    prefetchCount: 100
#    concurrentConsumers: 500

#quartz:
#  threadCount: 100


#logging
logging:
  level.com.pkk: debug
  level.java.sql.Connection: debug
  level.java.sql.Statement: debug
  level.java.sql.PreparedStatement: debug
